### ISSUE TITLE
html seems not working?

### ISSUE THREAD

**Issue by kimdn** [peikai/APT-point-cloud#1]
Thank you for coding this up.

However,
https://raw.githubusercontent.com/peikai/APT-point-cloud/master/output/H_O_Ca_Ga_N_C.html
on my chrome
led to
<img width="825" alt="Screen Shot 2022-02-18 at 2 27 03 PM" src="https://user-images.githubusercontent.com/3903446/154769505-24a2ac86-d50d-4b5e-af25-82ca77f5d1bd.png">

**Comment by peikai** [comment]
Sorry for late notice of this issue. To solve it, just download on local and reopen it. This because raw.github... always show the raw files, instead of rendering them.

![image](https://user-images.githubusercontent.com/25943913/218656252-b3861a15-9d0a-42e7-abae-fc3b46d1435b.png)

**Comment by kimdn** [comment]
Thank you. It is working now
<img width="907" alt="Screen Shot 2023-02-14 at 9 11 59 AM" src="https://user-images.githubusercontent.com/3903446/218808764-43536659-a851-4e1b-9a2e-a864c5880809.png">
